name: Create Doxygen documentation

on:
  push:
    # branches: [ $default-branch ]
    paths:
      - Code/CH_AS1100.cpp
      - Code/CH_AS1100.h

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.5
        with:
          doxyfile-path: ./Doxyfile
          working-directory: .

      - uses: stefanzweifel/git-auto-commit-action@v4
