name: Create Doxygen documentation

on:
  push:
    branches:
      - master
      - add/doxygen
    paths:
      - .github/workflows/doxygen.yml
      - Code/CH_AS1100.cpp
      - Code/CH_AS1100.h

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.5
        with:
          doxyfile-path: ./Doxyfile
          working-directory: .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
